# ===================================================
#
#              [ Monitors Configuation ]
# 
# ===================================================
# See https://wiki.hyprland.org/Configuring/Monitors/


# Default
# monitor=,preferred,auto,auto

# Customized Rules
monitor = eDP-1, preferred, auto, 1.5 # laptop screen
# monitor = DP-3, 2560x1440@59.95, auto, 1 # Samsung 43inch TV


# 06-10-2024: Fix XWayland Scaling for JetBrains IDE
xwayland {
  force_zero_scaling = true
}
