# ===================================================
#
#              [ Rules Configuation ]
# 
# ===================================================

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .* # You'll probably like this.
}
